<?php declare(strict_types=1);

use AdPage\GTM\Config\Config;

/** @var Config $config */
$config = $block->getConfig();

if ($config->isEnabled() && $config->getGoogleTagmanagerUrl() && strlen($config->getGoogleTagmanagerUrl()) > 0 && $config->isPlacedByPlugin()) {
echo "
<script defer src='https://{$config->getGoogleTagmanagerUrl()}/adex.js'></script>
<script defer src='https://{$config->getGoogleTagmanagerUrl()}/user-data-minified.es.js'></script>
<script defer src='https://{$config->getGoogleTagmanagerUrl()}/settings.js'></script>
";
}

if ($config->isEnabled() && $config->getGoogleTagmanagerUrl() && strlen($config->getGoogleTagmanagerUrl()) > 0) {
?>
    <script>
        function callUserData() {
            window.dataLayer = window.dataLayer || [];
            window.dataLayer.push({
                event: "trytagging_user_data",
                marketing: window.taggingHelpers.getMarketingObject(),
                device: window.taggingHelpers.getDeviceInfo(),
            });
        }

        document.addEventListener("DOMContentLoaded", function() {
            if (window.taggingHelpers) {
                callUserData();
            } else {
                setTimeout(function() {
                    if (window.taggingHelpers) {
                        callUserData();
                    } else {
                        console.log("taggingHelpers not available after wait");
                    }
                }, 750);
            }
        });
    </script>
<?php
}
?>