<?php declare(strict_types=1);

use AdPage\GTM\Config\Config;

/** @var Config $config */
$config = $block->getConfig();

if ($config->isEnabled() && $config->getGoogleTagmanagerUrl() && strlen($config->getGoogleTagmanagerUrl()) > 0) {
echo "
<script defer src='https://{$config->getGoogleTagmanagerUrl()}/adex.js'></script>
<script defer src='http://localhost:4500/user-data-minified.js'></script>
<script defer src='https://{$config->getGoogleTagmanagerUrl()}/settings.js'></script>
";
}
?>
