<?php declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use AdPage\GTM\Config\Config;

/** @var Config $config */
/** @var Template $block */
$config = $block->getConfig();
?>
<script>
    window.AdPage_GTM_ENABLED = true;

    (function (events) {
        const initgoogleTagManager2 = function () {
            events.forEach(function (eventType) {
                window.removeEventListener(eventType, initgoogleTagManager2);
            });

            <?= $config->getConfig() ?>
        }

        events.forEach(function (eventType) {
            window.addEventListener(eventType, initgoogleTagManager2, {once: true, passive: true})
        })
    })(['load']);
</script>

<?php if ($config->isDebug()): ?>
    <script>
        window.AdPage_GTM_DEBUG = true;
    </script>
<?php endif; ?>
